#Luke Thibodeaux C00096638
# echo ‘Response to Query #1';
SELECT Name, Gender, 2019-BirthYear AS Age FROM viewer;
# echo ‘Response to Query #2';
SELECT Name, Gender, 2019-BirthYear AS Age FROM viewer WHERE Gender = 'F' AND 2019-BirthYear > 30;
# echo ‘Response to Query #3';
SELECT Name, phone, Address FROM owner WHERE Address LIKE '%Raybern%';
# echo ‘Response to Query #4';
SELECT DISTINCT Name FROM viewer, likes WHERE viewer.SSN = likes.SSN;
# echo ‘Response to Query #5';
SELECT theatre_name, Name AS owner_name, owner.phone FROM owner, theatre WHERE owner.phone = theatre.phone;
# echo ‘Response to Query #6';
SELECT DISTINCT Name, Gender FROM viewer, likes WHERE viewer.fav_movie = likes.movie AND viewer.SSN = likes.SSN;
# echo ‘Response to Query #7';
SELECT DISTINCT Name, Gender FROM viewer, likes WHERE viewer.fav_movie != likes.movie AND likes.SSN = viewer.SSN;
# echo ‘Response to Query #8';
SELECT theatre_name FROM theatre, shows, movie WHERE theatre.theatre_name = shows.theatre AND shows.movies = movie.movie_name AND movie.genre = 'western';
# echo ‘Response to Query #9';
SELECT Name FROM owner WHERE owner.City = 'Port Alizemouth';
# echo ‘Response to Query #10';
SELECT DISTINCT movie_name FROM movie, shows, likes WHERE movie.movie_name = shows.movies AND movie.movie_name = likes.movie;
# echo ‘Response to Query #11';
SELECT DISTINCT Name, owner.phone FROM owner, theatre, shows WHERE owner.SSN = theatre.owner_ssn AND theatre.theatre_name = shows.theatre AND shows.movies != 'Forest Gump';
# echo ‘Response to Query #12';
SELECT A.Name, B.Name FROM viewer A, viewer B WHERE A.fav_movie = B.fav_movie;
SELECT COUNT(*) AS Numbers_of_Theatres_That_Show_Forrest_Gump FROM shows WHERE shows.movies = 'Forrest Gump';
# echo ‘Response to Query #14';
SELECT COUNT(DISTINCT movie) AS Total_Number_of_Movies_liked_by_Viewers FROM likes;
# echo ‘Response to Query #15';
SELECT Gender, COUNT(*) AS Number_of_Older_Viewers FROM viewer WHERE 2019-BirthYear > 64 GROUP BY Gender HAVING Count(Gender)>1; 